app:
  name: "appserver"
  tcpPort: ":8889"
  httpPort: ":8889"
  misKey: "md5key#@byonegames.com"
  openWs : "true"
  jsonPath: "./conf/json"
log:
  level: "debug"
  filePath: "./logs/info/%v.log"
  errFilePath: "./logs/err/%v.log"
  maxAge: 7
  maxSize: 128
  maxBackups: 5
  timeFormat: "2006-01-02 15:04:05.00000"
redis:
  addr: "192.168.1.113:6379"
  password: ""
  db: 1
  poolSize: 30
  minIdleConns: 30
databases:
  - dbType: "default"
    dsn: "root:123456@tcp(192.168.1.113:3306)/by_x2_app_1?charset=utf8&parseTime=True&loc=Local&timeout=5s"
    maxIdleCount: 10
    maxOpenCount: 100
    maxLifetime: 30m
    autoMigrate: true
  - dbType: "log"
    dsn: "root:123456@tcp(192.168.1.113:3306)/by_x2_log_1?charset=utf8&parseTime=True&loc=Local&multiStatements=true&timeout=5s"
    maxIdleCount: 10
    maxOpenCount: 100
    maxLifeTime: 30m
    autoMigrate: true
