databases:
  - db_type: "default"
    dsn: "root:123456@tcp(192.168.1.113:3306)/by_x2_app_1?charset=utf8&parseTime=True&loc=Local&timeout=5s"
    max_idle_count : 10
    max_open_count : 100
    max_lifetime : 30m
    auto_migrate: true
  - db_type: "log"
    dsn: "root:123456@tcp(192.168.1.113:3306)/by_x2_log_1?charset=utf8&parseTime=True&loc=Local&multiStatements=true&timeout=5s"
    max_idle_count: 10
    max_open_count: 100
    max_life_time: 30m
    auto_migrate: true